using UnityEngine;

/// <summary>
/// Applies a consistent base+highlight tint to a block without changing colliders.
/// Works with the multi-sprite textures generated by PrefabGenerator.
/// </summary>
[DisallowMultipleComponent]
public class BlockVisualStyle : MonoBehaviour
{
    [Header("Palette")]
    [Tooltip("If empty, a default 5-color palette is used.")]
    public Color[] palette;

    [Tooltip("Random seed override. If 0, uses instance id.")]
    public int seedOverride;

    [Header("Shading")]
    [Range(0f, 1f)]
    [Tooltip("How much brighter the highlight is compared to base.")]
    public float highlightToWhite = 0.35f;

    [Range(0f, 1f)]
    [Tooltip("Highlight alpha multiplier.")]
    public float highlightAlpha = 1f;

    [Header("Renderer")]
    public SpriteRenderer baseRenderer;
    public SpriteRenderer highlightRenderer;

    private static readonly Color[] DefaultPalette = new Color[]
    {
        new Color(0.20f, 0.62f, 1.00f, 1f), // blue
        new Color(0.28f, 0.86f, 0.55f, 1f), // green
        new Color(1.00f, 0.78f, 0.20f, 1f), // amber
        new Color(0.95f, 0.36f, 0.47f, 1f), // coral
        new Color(0.66f, 0.46f, 0.98f, 1f), // purple
    };

    private void Reset()
    {
        baseRenderer = GetComponent<SpriteRenderer>();
        if (highlightRenderer == null)
        {
            Transform t = transform.Find("Highlight");
            if (t != null) highlightRenderer = t.GetComponent<SpriteRenderer>();
        }
    }

    private void Awake()
    {
        if (baseRenderer == null)
        {
            baseRenderer = GetComponent<SpriteRenderer>();
        }
        if (highlightRenderer == null)
        {
            Transform t = transform.Find("Highlight");
            if (t != null) highlightRenderer = t.GetComponent<SpriteRenderer>();
        }
    }

    private void Start()
    {
        ApplyRandomStyle();
    }

    public void ApplyRandomStyle()
    {
        Color[] p = (palette != null && palette.Length > 0) ? palette : DefaultPalette;

        int seed = seedOverride != 0 ? seedOverride : GetInstanceID();
        var rng = new System.Random(seed);
        Color baseColor = p[rng.Next(0, p.Length)];

        ApplyStyle(baseColor);
    }

    public void ApplyStyle(Color baseColor)
    {
        if (baseRenderer != null)
        {
            baseRenderer.color = baseColor;
        }

        if (highlightRenderer != null)
        {
            Color highlight = Color.Lerp(baseColor, Color.white, Mathf.Clamp01(highlightToWhite));
            highlight.a *= Mathf.Clamp01(highlightAlpha);
            highlightRenderer.color = highlight;
        }
    }
}
